name: "Greetings"

on:
  push:
    branches:
      - "**" 
  issues:
    types: [opened] 
  pull_request:
    branches:
      - "**" 
    types: [opened] 

permissions:
  issues: write
  pull-requests: write

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Welcome, @${{ github.actor }}! Thanks for raising the issue.
            Soon the maintainers/owner will review it and provide you with feedback/suggestions.
            Make sure to **star this awesome repository** and **follow the account** for updates!
          pr-message: |
            Great job, @${{ github.actor }}! Thanks for creating the pull request.
            Soon the maintainers/owner will review it and provide you with feedback/suggestions.
            Make sure to **star this awesome repository** and **follow the account** for updates!
          footer: "Make sure to stay involved and contribute to the project!"
