# File location: .github/workflows/greetings.yml
name: Greetings Workflow  # Name of the workflow

on:  # Trigger events
  issues:
    types: [opened]  # Triggers when a new issue is opened
  pull_request_target:
    types: [opened]  # Triggers when a pull request is opened

jobs:
  greet:
    runs-on: ubuntu-latest  # OS for the runner

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3  # Checks out the repo

      - name: Run custom greeting action
        uses: ./  # This points to the root directory where action.yml resides

        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Passes the GitHub token
          issue-message: 'Welcome, @{{ github.actor }}! Thanks for opening this issue!'
          pr-message: 'Great job, @{{ github.actor }}! Thanks for the pull request!'
          footer: 'The maintainers will review your request soon. Stay tuned!'
